app/protected/models/CoachingContract.php
<?php

Yii::import('application.models._base.BaseCoachingContract');

class CoachingContract extends BaseCoachingContract
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
	
	public function __toString(){
		return	$this->coaching_contract_id;
	}
}

app/protected/controllers/CoachController.php
<?php

class CoachController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Coach'),
		));
	}

	public function actionCreate() {
		$model = new Coach;


		if (isset($_POST['Coach'])) {
			$model->setAttributes($_POST['Coach']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->coach_id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Coach');


		if (isset($_POST['Coach'])) {
			$model->setAttributes($_POST['Coach']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->coach_id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Coach')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Coach');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Coach('search');
		$model->unsetAttributes();

		if (isset($_GET['Coach']))
			$model->setAttributes($_GET['Coach']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

app/protected/controllers/CoachingContractController.php
<?php

class CoachingContractController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'CoachingContract'),
		));
	}

	public function actionCreate() {
		$model = new CoachingContract;


		if (isset($_POST['CoachingContract'])) {
			$model->setAttributes($_POST['CoachingContract']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->coaching_contract_id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'CoachingContract');


		if (isset($_POST['CoachingContract'])) {
			$model->setAttributes($_POST['CoachingContract']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->coaching_contract_id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'CoachingContract')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('CoachingContract');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new CoachingContract('search');
		$model->unsetAttributes();

		if (isset($_GET['CoachingContract']))
			$model->setAttributes($_GET['CoachingContract']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

app/protected/controllers/UserController.php
<?php

class UserController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'User'),
		));
	}

	public function actionCreate() {
		$model = new User;


		if (isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->user_id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'User');


		if (isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->user_id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'User')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('User');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new User('search');
		$model->unsetAttributes();

		if (isset($_GET['User']))
			$model->setAttributes($_GET['User']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

app/protected/views/coachingContract/_form.php
<div class="form">


<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'coaching-contract-form',
	'enableAjaxValidation' => false,
));
?>

	<p class="note">
		Fields with <span class="required">*</span> are required.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<div class="row">
		<?php echo $form->labelEx($model,'client_id'); ?>
		<?php echo $form->dropDownList($model, 'client_id', GxHtml::listDataEx(Client::model()->findAllAttributes(null, true)), array('empty'=>'') ); ?>
		<?php echo $form->error($model,'client_id'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'assignment_id'); ?>
		<?php echo $form->dropDownList($model, 'assignment_id', GxHtml::listDataEx(Assignment::model()->findAllAttributes(null, true)), array('empty'=>'') ); ?>
		<?php echo $form->error($model,'assignment_id'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'framework_id'); ?>
		<?php echo $form->dropDownList($model, 'framework_id', GxHtml::listDataEx(Framework::model()->findAllAttributes(null, true)), array('empty'=>'') ); ?>
		<?php echo $form->error($model,'framework_id'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'coach_id'); ?>
		<?php echo $form->dropDownList($model, 'coach_id', GxHtml::listDataEx(Coach::model()->findAllAttributes(null, true)), array('empty'=>'') ); ?>
		<?php echo $form->error($model,'coach_id'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'sponsor_id'); ?>
		<?php echo $form->dropDownList($model, 'sponsor_id', GxHtml::listDataEx(Sponsor::model()->findAllAttributes(null, true)), array('empty'=>'') ); ?>
		<?php echo $form->error($model,'sponsor_id'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'manager_id'); ?>
		<?php echo $form->textField($model, 'manager_id'); ?>
		<?php echo $form->error($model,'manager_id'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'manager_present'); ?>
		<?php echo $form->textField($model, 'manager_present', array('maxlength' => 1)); ?>
		<?php echo $form->error($model,'manager_present'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'sponsor_present'); ?>
		<?php echo $form->textField($model, 'sponsor_present', array('maxlength' => 1)); ?>
		<?php echo $form->error($model,'sponsor_present'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'initial_meeting_date'); ?>
		<?php $form->widget('zii.widgets.jui.CJuiDatePicker', array(
			'model' => $model,
			'attribute' => 'initial_meeting_date',
			'value' => $model->initial_meeting_date,
			'options' => array(
				'showButtonPanel' => true,
				'changeYear' => true,
				'dateFormat' => 'yy-mm-dd',
				),
			));
; ?>
		<?php echo $form->error($model,'initial_meeting_date'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'number_of_sessions'); ?>
		<?php echo $form->textField($model, 'number_of_sessions'); ?>
		<?php echo $form->error($model,'number_of_sessions'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'data_gathering_id'); ?>
		<?php echo $form->dropDownList($model, 'data_gathering_id', GxHtml::listDataEx(CoachingContractDataGathering::model()->findAllAttributes(null, true)), array('empty'=>'') ); ?>
		<?php echo $form->error($model,'data_gathering_id'); ?>
		</div><!-- row -->
			<div class="row">
		<?php echo $form->labelEx($model,'review_point'); ?>
		<?php echo $form->textField($model, 'review_point', array('maxlength' => 255)); ?>
		<?php echo $form->error($model,'review_point'); ?>
		</div><!-- row -->
	
 

<?php
echo GxHtml::submitButton('Save');
$this->endWidget();
?>
</div><!-- form -->

app/protected/views/coachingContract/_search.php
<div class="wide form">

<?php $form = $this->beginWidget('GxActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model, 'coaching_contract_id'); ?>
		<?php echo $form->textField($model, 'coaching_contract_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'client_id'); ?>
		<?php echo $form->dropDownList($model, 'client_id', GxHtml::listDataEx(Client::model()->findAllAttributes(null, true)), array('prompt' => 'All')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'assignment_id'); ?>
		<?php echo $form->dropDownList($model, 'assignment_id', GxHtml::listDataEx(Assignment::model()->findAllAttributes(null, true)), array('prompt' => 'All')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'framework_id'); ?>
		<?php echo $form->dropDownList($model, 'framework_id', GxHtml::listDataEx(Framework::model()->findAllAttributes(null, true)), array('prompt' => 'All')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'coach_id'); ?>
		<?php echo $form->dropDownList($model, 'coach_id', GxHtml::listDataEx(Coach::model()->findAllAttributes(null, true)), array('prompt' => 'All')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'sponsor_id'); ?>
		<?php echo $form->dropDownList($model, 'sponsor_id', GxHtml::listDataEx(Sponsor::model()->findAllAttributes(null, true)), array('prompt' => 'All')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'manager_id'); ?>
		<?php echo $form->textField($model, 'manager_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'manager_present'); ?>
		<?php echo $form->textField($model, 'manager_present', array('maxlength' => 1)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'sponsor_present'); ?>
		<?php echo $form->textField($model, 'sponsor_present', array('maxlength' => 1)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'initial_meeting_date'); ?>
		<?php $form->widget('zii.widgets.jui.CJuiDatePicker', array(
			'model' => $model,
			'attribute' => 'initial_meeting_date',
			'value' => $model->initial_meeting_date,
			'options' => array(
				'showButtonPanel' => true,
				'changeYear' => true,
				'dateFormat' => 'yy-mm-dd',
				),
			));
; ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'number_of_sessions'); ?>
		<?php echo $form->textField($model, 'number_of_sessions'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'data_gathering_id'); ?>
		<?php echo $form->dropDownList($model, 'data_gathering_id', GxHtml::listDataEx(CoachingContractDataGathering::model()->findAllAttributes(null, true)), array('prompt' => 'All')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'review_point'); ?>
		<?php echo $form->textField($model, 'review_point', array('maxlength' => 255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'record_created'); ?>
		<?php echo $form->textField($model, 'record_created'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'record_updated'); ?>
		<?php echo $form->textField($model, 'record_updated'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'created_by'); ?>
		<?php echo $form->dropDownList($model, 'created_by', GxHtml::listDataEx(User::model()->findAllAttributes(null, true)), array('prompt' => 'All')); ?>
	</div>

	<div class="row buttons">
		<?php echo GxHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

app/protected/views/coachingContract/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('coaching_contract_id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->coaching_contract_id), array('view', 'id' => $data->coaching_contract_id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('client')); ?>:
	<?php echo GxHtml::encode(GxHtml::valueEx($data->client)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('assignment')); ?>:
	<?php echo GxHtml::encode(GxHtml::valueEx($data->assignment)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('framework')); ?>:
	<?php echo GxHtml::encode(GxHtml::valueEx($data->framework)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('coach')); ?>:
	<?php echo GxHtml::encode(GxHtml::valueEx($data->coach)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('sponsor')); ?>:
	<?php echo GxHtml::encode(GxHtml::valueEx($data->sponsor)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('manager_id')); ?>:
	<?php echo GxHtml::encode($data->manager_id); ?>
	<br />
	<?php /*
	<?php echo GxHtml::encode($data->getAttributeLabel('manager_present')); ?>:
	<?php echo GxHtml::encode($data->manager_present); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('sponsor_present')); ?>:
	<?php echo GxHtml::encode($data->sponsor_present); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('initial_meeting_date')); ?>:
	<?php echo GxHtml::encode($data->initial_meeting_date); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('number_of_sessions')); ?>:
	<?php echo GxHtml::encode($data->number_of_sessions); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('dataGathering')); ?>:
	<?php echo GxHtml::encode(GxHtml::valueEx($data->dataGathering)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('review_point')); ?>:
	<?php echo GxHtml::encode($data->review_point); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('record_created')); ?>:
	<?php echo GxHtml::encode($data->record_created); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('record_updated')); ?>:
	<?php echo GxHtml::encode($data->record_updated); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('createdBy')); ?>:
	<?php echo GxHtml::encode(GxHtml::valueEx($data->createdBy)); ?>
	<br />
	*/ ?>

</div>

app/protected/views/coachingContract/admin.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	'Manage',
);

$this->menu = array(
		array('label'=>'List' . ' ' . $model->label(2), 'url'=>array('index')),
		array('label'=>'Create' . ' ' . $model->label(), 'url'=>array('create')),
	);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('coaching-contract-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo 'Manage' . ' ' . GxHtml::encode($model->label(2)); ?></h1>

<p>
You may optionally enter a comparison operator (&lt;, &lt;=, &gt;, &gt;=, &lt;&gt; or =) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<!-- <?php echo GxHtml::link('Advanced Search', '#', array('class' => 'search-button')); ?> -->

<!-- <div class="search-form"> -->
	
<!-- </div> -->
<!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'coaching-contract-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
		'coaching_contract_id',
		array(
				'name'=>'client_id',
				'value'=>'GxHtml::valueEx($data->client)',
				'filter'=>GxHtml::listDataEx(Client::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'assignment_id',
				'value'=>'GxHtml::valueEx($data->assignment)',
				'filter'=>GxHtml::listDataEx(Assignment::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'framework_id',
				'value'=>'GxHtml::valueEx($data->framework)',
				'filter'=>GxHtml::listDataEx(Framework::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'coach_id',
				'value'=>'GxHtml::valueEx($data->coach)',
				'filter'=>GxHtml::listDataEx(Coach::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'sponsor_id',
				'value'=>'GxHtml::valueEx($data->sponsor)',
				'filter'=>GxHtml::listDataEx(Sponsor::model()->findAllAttributes(null, true)),
				),
		/*
		'manager_id',
		'manager_present',
		'sponsor_present',
		'initial_meeting_date',
		'number_of_sessions',
		array(
				'name'=>'data_gathering_id',
				'value'=>'GxHtml::valueEx($data->dataGathering)',
				'filter'=>GxHtml::listDataEx(CoachingContractDataGathering::model()->findAllAttributes(null, true)),
				),
		'review_point',
		'record_created',
		'record_updated',
		array(
				'name'=>'created_by',
				'value'=>'GxHtml::valueEx($data->createdBy)',
				'filter'=>GxHtml::listDataEx(User::model()->findAllAttributes(null, true)),
				),
		*/
		array(
			'class' => 'CButtonColumn',
		),
	),
)); ?>

app/protected/views/coachingContract/create.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	'Create',
);

$this->menu = array(
	array('label'=>'List' . ' ' . $model->label(2), 'url' => array('index')),
	array('label'=>'Manage' . ' ' . $model->label(2), 'url' => array('admin')),
);
?>

<h1><?php echo 'Create' . ' ' . GxHtml::encode($model->label()); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

app/protected/views/coachingContract/index.php
<?php

$this->breadcrumbs = array(
	CoachingContract::label(2),
	'Index',
);

$this->menu = array(
	array('label'=>'Create' . ' ' . CoachingContract::label(), 'url' => array('create')),
	array('label'=>'Manage' . ' ' . CoachingContract::label(2), 'url' => array('admin')),
);
?>

<h1><?php echo GxHtml::encode(CoachingContract::label(2)); ?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); 

app/protected/views/coachingContract/update.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model) => array('view', 'id' => GxActiveRecord::extractPkValue($model, true)),
	'Update',
);

$this->menu = array(
	array('label' => 'List' . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => 'Create' . ' ' . $model->label(), 'url'=>array('create')),
	array('label' => 'View' . ' ' . $model->label(), 'url'=>array('view', 'id' => GxActiveRecord::extractPkValue($model, true))),
	array('label' => 'Manage' . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo 'Update' . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model));
?>

app/protected/views/coachingContract/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>'List' . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>'Create' . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>'Update' . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->coaching_contract_id)),
	array('label'=>'Delete' . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->coaching_contract_id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage' . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo 'View' . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
'coaching_contract_id',
array(
			'name' => 'client',
			'type' => 'raw',
			'value' => $model->client !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->client)), array('client/view', 'id' => GxActiveRecord::extractPkValue($model->client, true))) : null,
			),
array(
			'name' => 'assignment',
			'type' => 'raw',
			'value' => $model->assignment !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->assignment)), array('assignment/view', 'id' => GxActiveRecord::extractPkValue($model->assignment, true))) : null,
			),
array(
			'name' => 'framework',
			'type' => 'raw',
			'value' => $model->framework !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->framework)), array('framework/view', 'id' => GxActiveRecord::extractPkValue($model->framework, true))) : null,
			),
array(
			'name' => 'coach',
			'type' => 'raw',
			'value' => $model->coach !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->coach)), array('coach/view', 'id' => GxActiveRecord::extractPkValue($model->coach, true))) : null,
			),
array(
			'name' => 'sponsor',
			'type' => 'raw',
			'value' => $model->sponsor !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->sponsor)), array('sponsor/view', 'id' => GxActiveRecord::extractPkValue($model->sponsor, true))) : null,
			),
'manager_id',
'manager_present',
'sponsor_present',
'initial_meeting_date',
'number_of_sessions',
array(
			'name' => 'dataGathering',
			'type' => 'raw',
			'value' => $model->dataGathering !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->dataGathering)), array('coachingContractDataGathering/view', 'id' => GxActiveRecord::extractPkValue($model->dataGathering, true))) : null,
			),
'review_point',
'record_created',
'record_updated',
array(
			'name' => 'createdBy',
			'type' => 'raw',
			'value' => $model->createdBy !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->createdBy)), array('user/view', 'id' => GxActiveRecord::extractPkValue($model->createdBy, true))) : null,
			),
	),
)); ?>

<h2><?php echo GxHtml::encode($model->getRelationLabel('coachingContractAreas')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->coachingContractAreas as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('coachingContractArea/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>