app/protected/models/Framework.php
<?php

Yii::import('application.models._base.BaseFramework');

class Framework extends BaseFramework
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
}

app/protected/controllers/FrameworkController.php
<?php
class FrameworkController extends GxController {
public function actionView($id) {
$this->render('view', array(
			'model' => $this->loadModel($id, 'Framework'),
			
		));
	}
public function actionAddCompetence($id) {
	$param = array('framework_id'=>$id);
	$model = Framework::model()->findByAttributes($param); 
	$model=new Competence;
	$model->framework_id=$id;
	$model->name=$_POST['competence'];
	$model->save();
	$this->redirect(array('update', 'id' =>$id));
	}
	// Add contract section...
	
	public function actionAddContract($id) {
	$id;
	$param = array('framework_id'=>$id);
	$model=new CoachingContractSection;
	$model->framework_id=$id;	
	$model->heading=$_POST['contract'];			
	$model->summary=$_POST['summary'];	
	$model->save();		
	$this->redirect(array('update', 'id' =>$id));
	}
//Create  Framework 

	public function actionCreate() {
		$model = new Framework;
		
		if (isset($_POST['Framework'])) {
			$model->setAttributes($_POST['Framework']);

			if ($model->save()) {
				$sql="select max(framework_id) as framework_id from  framework";
				$command=Yii::app()->db->createCommand($sql);
				$rows=$command->queryAll();
				foreach($rows as $row)
				{
				$data=$row['framework_id'];
				}
			   $this->redirect(array('update', 'id' => $model->framework_id));
			}
			}
		

		$this->render('create', array( 'model' => $model));
	}
	
	
	//
	
	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Framework');


		if (isset($_POST['Framework'])) {
			$model->setAttributes($_POST['Framework']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->framework_id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
	echo $id;	
	echo $this->actionActiveDisable($id);
	exit;
	$command = Yii::app()->db->createCommand();
					$command->update('framework', array(
					'active'=>'N',
					), 'framework_id=:id', array(':id'=>$id));
          			 $this->redirect(array('admin'));
				
	
		if (Yii::app()->getRequest()->getIsPostRequest()) {
		$this->loadModel($id, 'Framework')->delete();

		if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Framework');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {

		$model = new Framework('search');
		
		$model->unsetAttributes();
		
		if (isset($_GET['Framework']))
	
			$model->setAttributes($_GET['Framework']);
			$this->render('admin', array(
			'model' => $model,
		));
	}
	
	public function actiondeleteOneCompetence() {
		$competenceid=$_REQUEST['competence_id'];
		$id=$_REQUEST['id'];
		$this->loadModel($competenceid, 'Competence')->delete();
		$this->redirect(array('update', 'id' => $id));
	}
	
		public function actiondeleteOneContractSection($id) {
		$id=$_REQUEST['id'];
		$contractsectionid=$_REQUEST['contract_section_id'];
		$this->loadModel($contractsectionid, 'CoachingContractSection')->delete();
		$this->redirect(array('update', 'id' => $id));
	}
	public function actionActiveDisable($id)
	{
	echo $id;
	$model = Framework::model()->findByPk($id);
	$model->active = 'N';
    $model->save();
	$this->redirect(array('admin'));
					 
}
	
	public function actionCreateAll() {
		$competence = new Competence;

		if (isset($_POST['Competence'])) {
			$competence->setAttributes($_POST['Competence']);

			if ($competence->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
//				else
//					$this->redirect(array('view', 'id' => $competence->competence_id));
			}
		}
		$framework = new Framework;
		if (isset($_POST['Framework'])) {
			$framework->setAttributes($_POST['Framework']);

			if ($framework->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
//				else
//					$this->redirect(array('view', 'id' => $model->framework_id));
			}
		}
		
		$coachingContractSection = new CoachingContractSection;
		if (isset($_POST['CoachingContractSection'])) {
			$coachingContractSection->setAttributes($_POST['CoachingContractSection']);
			if ($coachingContractSection->save()) 
			{
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				//else
//					$this->redirect(array('view', 'id' => $model->section_id));
			}
		}
				
		$this->render('createall', array(
			'framework' => $framework,
			'coachingContractSection' => $coachingContractSection,
			'competence' => $competence
		));
	}
}

app/protected/controllers/UserController.php
<?php

class UserController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'User'),
		));
	}

	public function actionCreate() {
		$model = new User;


		if (isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->user_id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'User');


		if (isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->user_id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'User')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('User');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new User('search');
		$model->unsetAttributes();

		if (isset($_GET['User']))
			$model->setAttributes($_GET['User']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

app/protected/views/framework/_form.php
<div class="form">

<?php 	$form = $this->beginWidget('GxActiveForm', array(
		'id' => 'framework-form',
		'enableAjaxValidation' => false,
		));

echo CHtml::link('Link Text',array('controller/action',
'param1'=>'value1')); 

?>
	<p class="note">

		Fields with <span class="required">*</span> are required.

	</p>
	<?php echo $form->errorSummary($model); ?>
	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>

		<?php echo $form->textField($model, 'name', array('class'=>'input-block-level', 'maxlength' => 50)); ?>

		<?php echo $form->error($model,'name'); ?>

		</div><!-- row -->

		<?php 

		
	echo GxHtml::submitButton('Save');

$this->endWidget();

?>

</div><!-- form -->


		

		

		

		

	

 

app/protected/views/framework/_formAll.php
<script>
function confirm()
{
var r=confirm("Are you sure gto delete");
if(r=='true')
{
alert("sds");
}
else if(r=='false')
{
alert("sdsd");
}
}
</script>	
<div class="form">


<?php
 $id=$_REQUEST['id'];
$form = $this->beginWidget('GxActiveForm', array(
	'id' => 'framework-form',
	'enableAjaxValidation' => false,
));
echo CHtml::link('Link Text',array('controller/action',
                                         'param1'=>'value1')); 
?>

	<p class="note">
		Fields with <span class="required">*</span> are required.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model, 'name', array('class'=>'input-block-level', 'maxlength' => 50)); ?>
		<?php echo $form->error($model,'name'); ?>
		</div><!-- row -->
<?php
echo "<div id='save'>";
 echo GxHtml::submitButton('Save');
 echo "</div>";
$this->endWidget();
?>
</div><!-- form -->
		
 <!--  ----------------------------------------Adding competnece  ---------------------------------------------------------------------------------->      
 <?php
        $form=$this->beginWidget('CActiveForm', 
        array('id'=>'AddForm',
        'action'=>Yii::app()->createUrl('framework/AddCompetence',array('id'=>$id)),
        'enableClientValidation'=>true,
       
        ));
        ?>
 <label style="font-size:14px;"> Competence Name</label> <br /> <input type="text" style="width:960px;" name="competence"  /> <br />
            
  <input type="submit" name="add" value="Add" />
       
        
       <?php $this->endWidget(); ?>  
       
<?php
 $id=$_REQUEST['id'];
		$base=Yii::app()->getBaseUrl();
		$dsn='localhost';
		$username='root';
		$password='';
		$connection=new CDbConnection($dsn,$username,$password);
		$connection=Yii::app()->db;
		
		$param = array('framework_id'=>$id);
		$rows = Competence::model()->findAllByAttributes($param); 
		
?>
 <table class="structure">
        
       	<?php if($rows) {  ?>
		 <tr class="portlet-decoration">
		 <th>Competence name</th>
		 </tr>
        
		 <?php
		 	}
		 $count = count($rows);
		$base=Yii::app()->getBaseUrl();
		for($i=0;$i<$count;$i++)
		{
			echo "<tr>";
			echo "<td>";
			$compId=$rows[$i]['competence_id'];
			echo CHtml::link($comp=$rows[$i]['name'],array('competence/update&id='.$compId)); 
			echo "<input type='hidden' value='$comp' name='competence[]'>";
			echo "</td>";
			echo "<td>";
			echo CHtml::link(
    	'<i class="icon-trash icon-red"></i>',
    	 array('framework/deleteOneCompetence','competence_id'=>$compId,'id'=>$id)
    	
		);
			echo "</td>";
			echo "</tr>";
		
		
		}
			 
		?>
      
       
		</table>	
		
		
		
	<br />
		<?php
        $form=$this->beginWidget('CActiveForm', 
        array('id'=>'AddForm',
        'action'=>Yii::app()->createUrl('framework/AddContract',array('id'=>$id)),
        'enableClientValidation'=>true,
       
        ));
        ?>

      <label style="font-size:14px;">  Contract Sections Name </label><br /> <input type="text"  style="width:960px;" name="contract"  /> <br /> 
       <label style="font-size:14px;">   Contract Section Summary </label><br /><textarea style="width: 965px; height: 202px;" name="summary"></textarea>  <br /><input type="submit" name="add_contract" value="Add" /> <br />
        
    <?php $this->endWidget(); ?>
        <br />
      <?php
	  
		$param = array('framework_id'=>$id);
		$row = CoachingContractSection::model()->findAllByAttributes($param); 
		 $count = count($row);
		if($row){
		?>
		<table class="structure">
		 <tr class="portlet-decoration">
		 <th>Contract Heading</th>
		 <th>Contract Summary</th>
		 </tr>
		 <?php
		 }
		for($i=0;$i<$count;$i++)
		{
			echo "<tr>";
			echo "<td>";
			$contId=$row[$i]['section_id'];
			echo CHtml::link($row[$i]['heading'],array('coachingContractSection/update&id='.$contId)); 
			echo "</td>";
			echo "<td>";
			echo CHtml::link($row[$i]['summary'],array('coachingContractSection/update&id='.$contId)); 
			echo "</td>";
			echo "<td>";
			echo CHtml::link(
    	'<i class="icon-trash icon-red"></i>',
    	 array('framework/deleteOneContractSection','contract_section_id'=>$contId,'id'=>$id),
    	 array('confirm' => 'Are you sure?')
		 
		);
		
			echo "</td>";
			echo "</tr>";
		
		
		}
		
		?>
		</table>
 


 
 

app/protected/views/framework/_search.php
<div class="wide form">

<?php $form = $this->beginWidget('GxActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model, 'framework_id'); ?>
		<?php echo $form->textField($model, 'framework_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'name'); ?>
		<?php echo $form->textField($model, 'name', array('maxlength' => 128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'active'); ?>
		<?php echo $form->textField($model, 'active', array('maxlength' => 1)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'record_created'); ?>
		<?php echo $form->textField($model, 'record_created'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'record_updated'); ?>
		<?php echo $form->textField($model, 'record_updated'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'created_by'); ?>
		<?php echo $form->dropDownList($model, 'created_by', GxHtml::listDataEx(User::model()->findAllAttributes(null, true)), array('prompt' => 'All')); ?>
	</div>

	<div class="row buttons">
		<?php echo GxHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

app/protected/views/framework/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('framework_id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->framework_id), array('view', 'id' => $data->framework_id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('name')); ?>:
	<?php echo GxHtml::encode($data->name); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('active')); ?>:
	<?php echo GxHtml::encode($data->active); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('record_created')); ?>:
	<?php echo GxHtml::encode($data->record_created); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('record_updated')); ?>:
	<?php echo GxHtml::encode($data->record_updated); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('createdBy')); ?>:
	<?php echo GxHtml::encode(GxHtml::valueEx($data->createdBy)); ?>
	<br />

</div>

app/protected/views/framework/admin.php
<?php
$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	'Manage',
);


$this->menu = array(
		//array('label'=>'List' . ' ' . $model->label(2), 'url'=>array('index')),
		array('label'=>'Create' . ' ' . $model->label(), 'url'=>array('create')),
	);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('framework-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo 'Manage' . ' ' . GxHtml::encode($model->label(2)); ?></h1>

<p>
You may optionally enter a comparison operator (&lt;, &lt;=, &gt;, &gt;=, &lt;&gt; or =) at the beginning of each of your search values to specify how the comparison should be done.

</p>


<!-- <?php echo GxHtml::link('Advanced Search', '#', array('class' => 'search-button')); ?> -->

<!-- <div class="search-form"> -->
	
<!-- </div> -->
<!-- search-form -->
<?php


 $image=Yii::app()->request->getBaseUrl();
?>
<a href="<?php echo $image?>/index.php?r=framework/create"><img src="<?php echo $image?>/images/NEW.png" /></a>

<?php $this->widget('zii.widgets.grid.CGridView', array(
'htmlOptions'=>array('style'=>'cursor: pointer;'),
'selectionChanged'=>"function(id){window.location='" . Yii::app()->urlManager->createUrl('framework/update', array('id'=>'')) . "' + $.fn.yiiGridView.getSelection(id);}",
	'id' => 'framework-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
	  array(
		'name'=>'framework_id',
		'htmlOptions'=>array('width'=>'25%'),
		
		 ),
		'name',
		array(
		'name'=>'active',
		//header=>"Competences",
		),
		array('header' => 'competences', 'value' => 'count($data->competences)'),


		array('header' => 'coachingContractSections', 'value' => 'count($data->coachingContractSections)'),
		
		/*array(
				'name'=>'created_by',
				'value'=>'GxHtml::valueEx($data->createdBy)',
				'filter'=>GxHtml::listDataEx(User::model()->findAllAttributes(null, true)),
				),
				*/
		/*array(
			'class' => 'CButtonColumn',
		),*/
		
		array(
		'class'=>'CButtonColumn',
		'template'=>'{delete}',

		),
             
       
	
	),
	
));
?>

app/protected/views/framework/create.php
<?php
$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	'Create',
);

$this->menu = array(
	array('label'=>'List' . ' ' . $model->label(2), 'url' => array('index')),
	array('label'=>'Manage' . ' ' . $model->label(2), 'url' => array('admin')),
);
?>
<h1><?php echo 'Create' . ' ' . GxHtml::encode($model->label()); ?></h1>
<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

app/protected/views/framework/index.php
<?php

$this->breadcrumbs = array(
	Framework::label(2),
	'Index',
);

$this->menu = array(
	array('label'=>'Create' . ' ' . Framework::label(), 'url' => array('create')),
	array('label'=>'Manage' . ' ' . Framework::label(2), 'url' => array('admin')),
);
?>

<h1><?php echo GxHtml::encode(Framework::label(2)); ?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); 

app/protected/views/framework/update.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model) => array('view', 'id' => GxActiveRecord::extractPkValue($model, true)),
	'Update',
);

$this->menu = array(
	array('label' => 'List' . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => 'Create' . ' ' . $model->label(), 'url'=>array('create')),
	array('label' => 'View' . ' ' . $model->label(), 'url'=>array('view', 'id' => GxActiveRecord::extractPkValue($model, true))),
	array('label' => 'Manage' . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo 'Update' . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_formAll', array(
		'model' => $model));
?>

app/protected/views/framework/view.php
<?php
 $id=$_REQUEST['id'];
$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);
$this->menu=array(
	array('label'=>'List' . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>'Create' . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>'Update' . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->framework_id)),
	array('label'=>'Delete' . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->framework_id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage' . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>
<h1><?php echo 'View' . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>
<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
'framework_id',
'name',
'active',
'record_created',
'record_updated',
array(
			'name' => 'createdBy',
			'type' => 'raw',
			'value' => $model->createdBy !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->createdBy)), array('user/view', 'id' => GxActiveRecord::extractPkValue($model->createdBy, true))) : null,
			),
	),
)); ?>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->assignments as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('assignment/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->coachingContracts as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('coachingContract/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>
<h2><?php echo GxHtml::encode($model->getRelationLabel('competences')); ?></h2>
 <?php
 $id=$_REQUEST['id'];
 $param = array('framework_id'=>$id);
$model123 = Competence::model()->findAllByAttributes($param); 
	$base=Yii::app()->getBaseUrl();	
		
?>
<table class="structure">
 <?php if($model123) {  ?>
		 <tr class="portlet-decoration">
		 <th>Competence name</th>
		 </tr>
        
		 <?php
		 	}
			foreach($model123 as $name)
		{
			echo "<tr>";
			echo "<td>";
			$compId=$name->attributes['competence_id'];
			echo "<a href='$base/index.php?r=competence/update&id=$compId'>". $comp=$name->attributes['name']. "</a>";
			
			echo "<input type='hidden' value='$comp' name='competence[]'>";
			echo "</td>";
			echo "<td>";
			echo CHtml::link(
    	'<i class="icon-trash icon-red"></i>',
    	 array('framework/deleteOneCompetence','competence_id'=>$compId,'id'=>$id)
    	
		);
			echo "</td>";
			echo "</tr>";
		}
		?>
      </table>	
	<br />
    <h2><?php echo GxHtml::encode($model->getRelationLabel('coachingContracts')); ?></h2>
        <br />
       <?php
		$param = array('framework_id'=>$id);
		$model123 = CoachingContractSection::model()->findAllByAttributes($param); 
	
		if($model123){
		
		?>
		<table class="structure">
		 <tr class="portlet-decoration">
		 <th>Contract Heading</th>
		 <th>Contract Summary</th>
		 </tr>
		 <?php
		 }
		foreach ($model123 as $name)
		{
			echo "<tr>";
			echo "<td>";
			$contId=$name->attributes['section_id'];
			echo  "<a href='$base/index.php?r=coachingContractSection/update&id=$contId'>". $name->attributes['heading']. "</a>";
			echo "</td>";
			echo "<td>";
			echo "<a href='$base/index.php?r=coachingContractSection/update&id=$contId'>" . $name->attributes['summary'] . "</a>";
			echo "</td>";
			echo "<td>";
			echo CHtml::link(
    	'<i class="icon-trash icon-red"></i>',
    	 array('framework/deleteOneContractSection','contract_section_id'=>$contId,'id'=>$id),
    	 array('confirm' => 'Are you sure?')
		 );
		    echo "</td>";
			echo "</tr>";
		}
		
		?>
		</table>